name: tests

on: [push, pull_request]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev libmpfr-dev libmpc-dev libgmp3-dev

      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        uses: abatilo/actions-poetry@v1.8.1
        with:
          python_version: 3.8.0
          poetry_version: 1.0.5
          args: install

      - name: Run lint
        run: |
          make lint

      - name: Run test
        run: |
          make test
